services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # Environment variables for the container to connect to the db service
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password # Use a more secure password in a real project
    depends_on:
      - db
    command: tail -f /dev/null

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user # A user is created, but we'll use root for simplicity in the app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      # Expose the port to the host machine for easier database access if needed
      - "3306:3306"
    # Added a healthcheck to ensure the app container doesn't start before mysql is ready
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10 