services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    # Environment variables for the container to connect to the db service
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password # Use a more secure password in a real project
    ports:
      - "8080:80"  # Map container port 80 to host port 8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user # A user is created, but we'll use root for simplicity in the app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      # Expose the port to the host machine for easier database access if needed
      - "3306:3306"
    # Added a healthcheck to ensure the app container doesn't start before mysql is ready
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql # Persistenza dati MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8081:80" # phpMyAdmin disponibile su http://localhost:8081
    depends_on:
      - db

volumes:
  mysql_data: 